### ISSUE TITLE
Help with documentation 

### ISSUE THREAD

**Issue by gabbianiiii** [pacheco7/MacGyver#2]
Need a help with documentation.

**Comment by kanlanc** [comment]
For which one?

**Comment by gabbianiiii** [comment]
For all interfaces. I need a person with skills in SAP ABAP :)

**Comment by pawelwiejkut** [comment]
Hi pacheco7, today I cloned your development and I want to help. Could you please describe what exactly you expect? Maybe some example?

**Comment by gabbianiiii** [comment]
Hi @pawelwiejkut !

Well, I’ll try to explain what is this project. “MacGyver” was created for facilitating the life of all beginner developer in SAP world, presenting a collection of useful algorithms to accelerate your developments. For this moment I need to document in English all interfaces in the wiki page of this project.

**Comment by pawelwiejkut** [comment]
Hi @pacheco7,
I think I can't edit your wiki, even after fork repository, could you please check is this possible? If not, maybe I can describe this interfaces in some different way, to be able to create a pull request?

**Comment by gabbianiiii** [comment]
Hi @pawelwiejkut, I sent to you a invite.
