### ISSUE TITLE
New accelerators

### ISSUE THREAD

**Issue by gabbianiiii** [pacheco7/MacGyver#4]
This issue is open to all who want to contribute with create new programs what can be useful to anothers.

How to contribute:

- The program must be strutured in one interface already created;
- The program can't be a routine what make one or more business roles;
- The program must have a unit test;
- The program must have a documentation.

**Comment by pawelwiejkut** [comment]
Added method for get end of month date

**Comment by gabbianiiii** [comment]
Inserted ;)
